[WEEK-1/ASSIGN-2] compoleted all the task assigned in assignment 2
pesto-students/p13-nishant-naithani-surajnikhade pull request #3
Opened 2023-08-05 13:21 UTC by surajnikhade

### Completed following webapages assigned in asssignment-2:

- Poem Webpage
- Hometown Webpage 
- Your Favourite Musician Fan Webpage 
- HTML Table and List
- News Article Webpage

2023-08-07 15:59 UTC, NishantNaithani commented
@surajnikhade ,

Added comments.

Thanks

2023-08-07 16:08 UTC, NishantNaithani requested changes

2023-08-07 16:08 UTC, NishantNaithani commented on Week-1/Assignment-2/hometown.html
> +      <div class="page__wrapper-location">
`-location` class is not defined in the `hometown.css` file

2023-08-07 16:08 UTC, NishantNaithani commented on Week-1/Assignment-2/hometown.css
> +.page__wrapper{
We can use single `_` here.

2023-08-07 16:08 UTC, NishantNaithani commented on Week-1/Assignment-2/poem.html
> +    <p>
Here always wrap your webpage content under a parent tag,
For e.g. `<main><p>......</p></main>`

2023-08-09 16:28 UTC, surajnikhade commented on Week-1/Assignment-2/hometown.html
> +      <div class="page__wrapper-location">
Since it didn't require any styling, I hadn't defined it in the .css file. Now, I have removed the class since it wasn't being used.

2023-08-10 05:26 UTC, NishantNaithani approved these changes

2023-08-10 05:26 UTC, NishantNaithani commented
@surajnikhade 
LGTM

2023-08-19 16:50 UTC, merged