WEEK-2/ASSIGMENTS
pesto-students/p13-nishant-naithani-surajnikhade pull request #5
Opened 2023-08-13 16:13 UTC by surajnikhade

2023-08-16 05:57 UTC, NishantNaithani requested changes

2023-08-16 05:57 UTC, NishantNaithani commented on Week-2/Assignment-1/favourite-musician.html
Here, `<footer></footer>` should be used for the footer related things.

2023-08-16 05:57 UTC, NishantNaithani commented on Week-2/Assignment-1/line-up.html
> +        </fieldset>
Here, we don't need to wrap the `Game Date` component inside `<fieldset>...</fieldset>`

2023-08-16 05:57 UTC, NishantNaithani commented on Week-2/Assignment-2/auto-loan.html
> +    <div class="container">
Here,
1. Please wrap all your content in a parent tag.
2. The `Heading` and the `content` is not sync with each other.

2023-08-16 05:57 UTC, NishantNaithani commented on Week-2/Assignment-2/news-article.html
Here, wrap your main content under a parent tag.

2023-08-16 05:57 UTC, NishantNaithani commented on Week-2/Assignment-2/sleep-reccomendation.html
Here, `source` content is missing.

2023-08-16 05:59 UTC, NishantNaithani commented
@surajnikhade ,
1. I believe the `Advanced CSS` assignment is missing.
2. CSS file indentations needs to be fixed.

Thanks

2023-08-19 07:39 UTC, surajnikhade reviewed
I have pushed week-2 assignement -3  also resolved pervious comments . Please check and LMK if changes required.
@NishantNaithani  
Thanks!

2023-08-31 04:56 UTC, NishantNaithani approved these changes

2023-08-31 04:56 UTC, merged